// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Kline-x/gokit/component/log"
	"github.com/Kline-x/gokit/example/minimal/internal/greeter/interfaces"
	"github.com/Kline-x/gokit/example/minimal/internal/greeter/remote"
)

// Injectors from wire.go:

// initApp 装配入口服务。
//
// 与 cmd/monolith 的装配比一比，差别只有两处：
// 这里用 greeter.RemoteSet 而不是 LocalSet，以及多提供一条 gRPC 连接。
// domain、application、interfaces 三层的代码一行没动。
func initApp(cfg Config) (*Bundle, error) {
	config := provideLogConfig(cfg)
	logger, err := log.New(config)
	if err != nil {
		return nil, err
	}
	app := provideApp(logger)
	httpserverConfig := provideHTTPConfig(cfg)
	grpcclientConfig := provideGreeterConfig(cfg)
	client, err := provideGreeterClient(grpcclientConfig)
	if err != nil {
		return nil, err
	}
	service := remote.NewService(client)
	httpHandler := interfaces.NewHTTPHandler(service)
	handler := provideHandler(logger, httpHandler)
	server := provideHTTPServer(httpserverConfig, handler, app)
	v := provideComponents(logger, client, server)
	bundle := &Bundle{
		App:        app,
		HTTP:       server,
		Components: v,
	}
	return bundle, nil
}
