// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Kline-x/gokit/component/log"
	"github.com/Kline-x/gokit/example/minimal/internal/greeter/interfaces"
	"github.com/Kline-x/gokit/example/minimal/internal/greeter/remote"
)

// Injectors from wire.go:

// initApp 装配入口服务。
//
// 与 cmd/monolith 的装配比一比，核心差异只有一处：这里用 greeter.RemoteSet
// 而不是 LocalSet，于是问候能力从「本进程实现」变成了「调远程」。
//
// 其余的出入都是这个选择的后果：既然实现不在本进程，就不需要数据库、
// 不需要事务能力的绑定，转而需要一条到下游的连接；本服务也不对外提供 gRPC，
// 所以 gRPC 服务端那套装配整个不在。逐行 diff 会看到七处不同，
// 但它们全是「换了一个 ProviderSet」推导出来的，不是七个独立决定。
//
// 真正的重点是没变的部分：domain、application、interfaces 三层一行没动。
func initApp(cfg Config) (*Bundle, error) {
	config := provideLogConfig(cfg)
	logger, err := log.New(config)
	if err != nil {
		return nil, err
	}
	app := provideApp(logger)
	httpserverConfig := provideHTTPConfig(cfg)
	grpcclientConfig := provideGreeterConfig(cfg)
	client, err := provideGreeterClient(grpcclientConfig)
	if err != nil {
		return nil, err
	}
	service := remote.NewService(client)
	httpHandler := interfaces.NewHTTPHandler(service)
	handler := provideHandler(logger, httpHandler)
	server := provideHTTPServer(httpserverConfig, handler, app)
	v := provideComponents(logger, client, server)
	bundle := &Bundle{
		App:        app,
		HTTP:       server,
		Components: v,
	}
	return bundle, nil
}
