log:
  level: info
  format: json
  output: stdout

http:
  addr: ":8080"
  read_timeout: 15s
  write_timeout: 15s

grpc:
  name: "grpcserver"
  addr: ":9000"
  shutdown_timeout: 10s
  enable_reflection: true

db:
  driver: sqlite
  dsn: "file:minimal.db"
  max_open_conns: 10
