// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Kline-x/gokit/component/log"
	"github.com/Kline-x/gokit/component/sqldb"
	"github.com/Kline-x/gokit/example/minimal/internal/greeter/application"
	"github.com/Kline-x/gokit/example/minimal/internal/greeter/infrastructure"
	"github.com/Kline-x/gokit/example/minimal/internal/greeter/interfaces"
)

import (
	_ "modernc.org/sqlite"
)

// Injectors from wire.go:

// initApp 由 wire 在编译期生成实现：按依赖关系把各组件与业务模块装配起来。
//
// 本文件与 provideComponents 一起构成组合根。把 greeter.LocalSet 换成
// greeter.RemoteSet，用法见 cmd/gateway，就能把该模块切成远程调用；同时要改的
// 还有 provideComponents 的入参，以及 wire.Build 里那些只为这个模块服务、
// 换成远程后不再需要的共享基础设施。业务代码——domain、application、
// interfaces 三层——一行都不用动，这才是这套分层想换来的东西。
func initApp(cfg Config) (*Bundle, error) {
	config := provideLogConfig(cfg)
	logger, err := log.New(config)
	if err != nil {
		return nil, err
	}
	app := provideApp(logger)
	httpserverConfig := provideHTTPConfig(cfg)
	sqldbConfig := provideDBConfig(cfg)
	db, err := sqldb.New(sqldbConfig)
	if err != nil {
		return nil, err
	}
	greetingRepo := infrastructure.NewGreetingRepo(db)
	localService := application.NewLocalService(greetingRepo, db)
	httpHandler := interfaces.NewHTTPHandler(localService)
	handler := provideHandler(logger, httpHandler)
	server := provideHTTPServer(httpserverConfig, handler, app)
	grpcserverConfig := provideGRPCConfig(cfg)
	grpcHandler := interfaces.NewGRPCHandler(localService)
	v := provideServiceRegistrars(grpcHandler)
	grpcserverServer := provideGRPCServer(grpcserverConfig, v, logger, app)
	migrator := infrastructure.NewMigrator(db)
	v2 := provideComponents(logger, db, migrator, server, grpcserverServer)
	bundle := &Bundle{
		App:        app,
		HTTP:       server,
		GRPC:       grpcserverServer,
		Components: v2,
	}
	return bundle, nil
}
