// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Kline-x/gokit/component/log"
	"github.com/Kline-x/gokit/component/sqldb"
	"github.com/Kline-x/gokit/example/minimal/internal/greeter/application"
	"github.com/Kline-x/gokit/example/minimal/internal/greeter/infrastructure"
	"github.com/Kline-x/gokit/example/minimal/internal/greeter/interfaces"
)

import (
	_ "modernc.org/sqlite"
)

// Injectors from wire.go:

// initApp 装配问候服务。
//
// 用的是 greeter.LocalSet —— 本进程就是这个模块的家，
// 仓储、建表、业务实现全在这里。
func initApp(cfg Config) (*Bundle, error) {
	config := provideLogConfig(cfg)
	logger, err := log.New(config)
	if err != nil {
		return nil, err
	}
	app := provideApp(logger)
	grpcserverConfig := provideGRPCConfig(cfg)
	sqldbConfig := provideDBConfig(cfg)
	db, err := sqldb.New(sqldbConfig)
	if err != nil {
		return nil, err
	}
	greetingRepo := infrastructure.NewGreetingRepo(db)
	localService := application.NewLocalService(greetingRepo, db)
	grpcHandler := interfaces.NewGRPCHandler(localService)
	v := provideServiceRegistrars(grpcHandler)
	server := provideGRPCServer(grpcserverConfig, v, logger, app)
	migrator := infrastructure.NewMigrator(db)
	v2 := provideComponents(logger, db, migrator, server)
	bundle := &Bundle{
		App:        app,
		GRPC:       server,
		Components: v2,
	}
	return bundle, nil
}
