// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Kline-x/gokit/component/log"
	"github.com/Kline-x/gokit/component/sqldb"
	"github.com/Kline-x/gokit/example/minimal/internal/greeter/application"
	"github.com/Kline-x/gokit/example/minimal/internal/greeter/infrastructure"
	"github.com/Kline-x/gokit/example/minimal/internal/greeter/interfaces"
)

import (
	_ "modernc.org/sqlite"
)

// Injectors from wire.go:

// initApp 由 wire 在编译期生成实现：按依赖关系把各组件与业务模块装配起来。
// 换掉 greeter.LocalSet 就能把该模块切成远程调用，这里是唯一需要改的地方。
func initApp(cfg Config) (*Bundle, error) {
	config := provideLogConfig(cfg)
	logger, err := log.New(config)
	if err != nil {
		return nil, err
	}
	app := provideApp(logger)
	sqldbConfig := provideDBConfig(cfg)
	db, err := sqldb.New(sqldbConfig)
	if err != nil {
		return nil, err
	}
	httpserverConfig := provideHTTPConfig(cfg)
	greetingRepo := infrastructure.NewGreetingRepo(db)
	localService := application.NewLocalService(greetingRepo, db)
	httpHandler := interfaces.NewHTTPHandler(localService)
	handler := provideHandler(logger, httpHandler)
	server := provideHTTPServer(httpserverConfig, handler, app)
	bundle := &Bundle{
		App:    app,
		Logger: logger,
		DB:     db,
		HTTP:   server,
	}
	return bundle, nil
}
